FROM mongo:3.4.4
LABEL maintainer_1="Rubén Vasallo <ruben@vasallo.nom.es>" \
      maintainer_2="David Sola <d.sola.03@gmail.com>"

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm-256color
ENV LANG C.UTF-8

# System Timezone
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
